### ISSUE TITLE
Issue with getting token

### ISSUE THREAD

**Issue by AndyFelton** [samcolby/react-native-ms-adal#2]
Hi,

I am trying to use this module to be able to get access to the Microsoft Graph API for Azure B2C. I can see the call going all the way to acquireTokenAsync in AuthenticationContext.js but then the application appears to crash after calling the RNAdalPlugin. 

I'm running this on an Android device and was wondering if I had some setup/configuration missing?

Thanks for any help you can provide
Andy

**Comment by AndyFelton** [comment]
Think I may have solved that some configuration missing from AndriodManifest.xml.

Thanks
Andy

**Comment by samcolby** [comment]
Ah good news!  And you preempted my reply...

Do you have any details on what you were missing in case it comes up again.

**Comment by AndyFelton** [comment]
Hi,

I think this was the line that got it working:
    <activity
        android:name="com.microsoft.aad.adal.AuthenticationActivity"
        android:label="@string/app_name">
    </activity>

Thanks for coming back so quickly!

One query I have got is we're using Azure B2C and have successfully completed an oAuth to that and have a bearer token. I need the ability to get claims and update details and was looking to use the Graph API for that. With this library how do I get access to the Graph API without going through another oAuth - or am I missing something on using B2C - all new to me sorry. If you have access to an example or some further detail that would be great!

Thanks
Andy

**Comment by AndyFelton** [comment]
Sorry the change to the AndroidManifest didn't get through is was
`    <activity
        android:name="com.microsoft.aad.adal.AuthenticationActivity"
        android:label="@string/app_name">
    </activity>`

Thanks

**Comment by samcolby** [comment]
Hi,

I'm no expert on the Azure side of things I'm afraid and not near a PC to check the code atm.

I'm fairly sure you need a separate oath token per resourceurl though. 

Pretty much all the code here is from the original Cordova library, you may have better luck asking there.  We just created the react native wrapper for it.

Thanks
Sam

**Comment by samcolby** [comment]
Hey Andy, @bjartebore pushed some code earlier that improves connecting to multiple resources.  Hopefully that helps you in some way.  I've marked this as version 0.3.1
