### ISSUE TITLE
Unable to authenticate multiple resources

### ISSUE THREAD

**Issue by bjartebore** [samcolby/react-native-ms-adal#3]
When trying to acquire token for multiple resources I am forced to run the full login process for each login. This seems to be because the promptBehaviour is set to "Always". 

If this is changed to Auto the application could decide for itself whether or not it would have to show the login dialog. We need to run the requireTokenAsync for each resource before we are able to use the requireTokenSilentlyAsync for the resource.

**Comment by samcolby** [comment]
see https://github.com/samcolby/react-native-ms-adal/commit/f62df90086c44324dbf1a92ee80d759d567f9e72
