### ISSUE TITLE
getValidMSAdalToken should skip over cache entries with no accessToken

### ISSUE THREAD

**Issue by olivergeorge** [samcolby/react-native-ms-adal#9]
I'm seeing cases where the last token in the cache has accessToken set to nil.

I _think_ the correct approach should be for `getValidMSAdalToken` to filter out cache entries with no accessToken value.

I'm not super confident how the token cache items should be treated but here's an example of code checking for an accessToken value and whether it's expired:
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/20e97dba0a7ef0bd3ba86c1aa93a0be5dcff3b71/ADAL/src/request/ADAcquireTokenSilentHandler.m#L322

**Comment by olivergeorge** [comment]
Example of the cache tokens I'm seeing:
![image](https://user-images.githubusercontent.com/99447/40825394-c2e98db6-65ba-11e8-818a-7e77bf023af4.png)

**Comment by olivergeorge** [comment]
It looks like the token entries in question are MRRT token cache items.  

https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/962ce25365320e9eb58a90f7070f46520e2c5733/adal/src/main/java/com/microsoft/aad/adal/TokenCacheItem.java#L151

**Comment by olivergeorge** [comment]
Final thought for now. The correct strategy might be filtering on resource. 

http://www.cloudidentity.com/blog/2013/10/01/getting-acquainted-with-adals-token-cache/

**Comment by samcolby** [comment]
Hi Oliver,

It's been a while since I've looked at this and no longer have an azure instance to test against (new job etc, etc), so you probably know more than I do now!  

You may be right about the multiple resource tokens.  This was something we added onto this library as the original cordova version didn't support it.  

Do you think we just need to update the [getValidMSAdalToken](https://github.com/samcolby/react-native-ms-adal/blob/b580f141b8ce6c9cdc44f40003d20418ddebb0ec/MSAdal.js#L50) function to loop back through cache and check if we have an accessToken?  

Something like (off the top of my head, untested and ignoring the resource filtering for simplicity)

``` javascript
function getValidMSAdalToken(authority) {
  let context = new AuthenticationContext(authority);
  return context.tokenCache.readItems().then(function(items) {
    for (i = items.length - 1; i >= 0; i--) { 
      let lastToken = items[i];
      if ( lastToken.accessToken && lastToken.expiresOn > new Date() ) { 
        return new AuthenticationResult(lastToken);
      } 
    }
  });
}
```

Sam

**Comment by olivergeorge** [comment]
Hi Sam,

That would work but I think perhaps you should check the resourceUri matches too.

```
function getValidMSAdalToken(authority, resourceUri) {
  let context = new AuthenticationContext(authority);
  return context.tokenCache.readItems().then(function(items) {
    for (i = items.length - 1; i >= 0; i--) { 
      let token = items[i];
      if ( token.accessToken && token.resource == resourceUri && token.expiresOn > new Date() ) { 
        return new AuthenticationResult(token);
      } 
    }
  });
}
```

As an aside, I'm starting to question the use case for `getValidMSAdalToken` over `acquireTokenSilentAsync`.

The doc string says:

> Acquires token WITHOUT using interactive flow. It checks the cache to return existing result
> if not expired. It tries to use refresh token if available. If it fails to get token without
> displaying UI it will fail. This method guarantees that no UI will be shown to user.

For my purposes, I want a non-interactive way of getting a valid access token before sending out a fetch request.  I thought getValidMSAdalToken was for that purpose but it doesn't do any token refreshing stuff.  

Instead, I really just an equivalent call to `acquireTokenSilentAsync`.

```
function acquireTokenSilentAsync(authority, resourceUri, clientId) {
  return context.acquireTokenSilentAsync(resourceUri, clientId);
}
```

As well as a patch for `getValidMSAdalToken` I suggest adding a `acquireTokenSilentAsync` fn to the api.

**Comment by samcolby** [comment]
Hi, 

You can just use MSAdalLogin to get the token.  This will do the aquireTokenSilentAsync call for you.  Call MSAdalLogin before every request and you should be good to go.   You'd need to do this anyway so you can handle cases where the app resumes from the background on deeper screen.

From memory, I only ever used getValidMSAdalToken as a quicker way to test if the current user was logged in.  Like when the app resumes from the background and I just need to know if they still have access.  

I hope that makes sense.  

Still looks like there might be a bug in getValidMSAdalToken code though.  Although you're the first person to notice.  Are you using multiple resources in your app?

Sam

**Comment by samcolby** [comment]
There's a new branch [getValidMSAdalToken](https://github.com/samcolby/react-native-ms-adal/tree/getValidMSAdalToken) with those changes in, if you want to test them.

**Comment by olivergeorge** [comment]
Thanks, I'll try it out.  Looks sane.
